src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('accounts/',include('accounts.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns +=static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)
urlpatterns +=doc_urls

my_app/models.py
from django.db import models
from accounts.models import User

class Menu(models.Model):
	Name =models.CharField(max_length =100)
	Descreption =models.TextField()
	Price =models.FloatField(max_length =10)
	Image =models.ImageField(upload_to='image/')

	def __str__(self):
		return self.Name 

class Comment(models.Model):
	userName =models.CharField(max_length =150)
	phone =models.CharField(max_length =20)
	email =models.CharField(max_length =50)
	message =models.TextField()
	date =models.DateTimeField(auto_now_add =True)

	def __str__(self):
		return f'{self.userName}'



#Model for adding the product to the card
class Order(models.Model):
	customer = models.ForeignKey(User, on_delete=models.SET_NULL,blank=True,null=True)
	date_orderd = models.DateTimeField(auto_now_add=True)
	name  = models.CharField(max_length=200, null=True)
	complete = models.BooleanField(default=False,null=True,blank=False)

#for calculating all the products in orderItem(products in card) by the function of get_total below 
	@property # Dekorator
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property # Dekorator
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total  = sum([item.quantity for item in orderitems])
		return total


	def __str__(self):
		return str(self.id)

class OrderItem(models.Model):
	product = models.ForeignKey(Menu, on_delete=models.SET_NULL,blank=True,null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL,blank=True,null=True)
	quantity = models.IntegerField(default=0,null=True,blank=True)
	date_added = models.DateTimeField(auto_now_add=True)


	@property # Dekorator
	def get_total(self):
		total = self.product.Price * self.quantity
		return total

	def __str__(self):
		return str(self.id)

templates/about.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Max-Burger </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- css files created by backend dev -->
  <link href="{% static 'css/style_2.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/view.css' %}" rel="stylesheet" type="text/css" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

 <script type="text/javascript"> 
  var user = '{{ request.user }}'

  function getToken(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}
var csrftoken = getToken('csrftoken');
  </script>
  
</head>

<div class="hero_area">
  <div class="bg-box-header" style="padding-top: 90px;"> 
    <img src="{% static 'images/fast-food.jpg' %}" alt="">
  </div>
  <!-- header section strats -->
  <header class="header_section">
    <div class="container">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="{% url 'home' %}">
          <span>
            MAX-BURGER
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav  mx-auto ">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'menu' %}">Меню</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">О нас</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'book' %}">Бук тэйбл</a>
            </li>
          </ul>
          <div class="user_option">
            {% if user.is_authenticated %}
            <div class="dropdown">
              <button class="add-to-cart1" style="margin-left: -100px"> {{ user.username|title }} </button>
              <div class="dropdown-content">
                <a href="#">Link 1</a>
                <a href='#'>Link 2</a>
                <a href="{% url 'logout' %}">Log out</a>
              </div>
            </div>

            <div>
              <a href="{% url 'cart' %}">
                <img id="cart-icon" style="margin-left: 20px; width:90px;" src="{% static 'images/cartt.png' %}">
              </a>
              <p id="cart-total" style="margin-left: 54px; margin-top: -23px">{{ cartItems }}</p>
            </div>

            {% else %}
            <form class="form-inline ml-auto">

              <a href="{% url 'signup' %}" class="order_online" style="margin: 15px;">
              Зарегистрироваться</a>
              <a href="{% url 'login' %}" class="order_online">
              Войти</a>
            </form>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
  </header>


  <!-- end header section -->

 <!-- about section -->
</div>

  <section class="about_section layout_padding" style="background-color:#FF375B; height: 300px;">
    <div class="container">
      <div class="row" style="width: 940px;">

        <div class="col-md-6" style="width: 200px; margin-top: -910px; background-color: #FF375B; padding: 40px 0; padding-left: 30px; margin-left: 13px; border-radius: 5px">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                Мы Макс-Бургер
              </h2>
            </div>
          <p> В рамках спецификации современных стандартов,<br> представители современных. <br>Cоциальных резервов будут заблокированы в рамках <br>своих собственных рациональных ограничений.<br> Наше дело не так однозначно, 
          </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  <body>
    <footer class="footer_section">
      <div class="container">
        <div class="row">
          <div class="col-md-4 footer-col">
            <div class="footer_contact">
              <h4>
                Связаться с нами
              </h4>
              <div class="contact_link_box">
                <a href="">
                  <i class="fa fa-map-marker" aria-hidden="true"></i>
                  <span>
                    Местоположение
                  </span>
                </a>
                <a href="">
                  <i class="fa fa-phone" aria-hidden="true"></i>
                  <span>
                    Звоните (90) 722-95-29
                  </span>
                </a>
                <a href="">
                  <i class="fa fa-envelope" aria-hidden="true"></i>
                  <span>
                    mukhammadali222@gmail.com
                  </span>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-4 footer-col">
            <div class="footer_detail" >
              <a href="" class="footer-logo" style="border: solid 2px white; margin-bottom: 20px; padding: 5px 15px;
              ">
                MAX-BURGER 
              </a>
              <p style="color:white">
                Следует отметить, что синтетическое тестирование прекрасно подходит для реализации инновационных методов управления процессами
              </p>
            </div>
          </div>
          <div class="col-md-4 footer-col">
            <h4>
              Часы работы
            </h4>
            <p style="color:white">
              Ежедневный
            </p>
            <p style="color:white">
              10.00 - 22.00
            </p>
          </div>
        </div>
        <div class="footer-info">
          <p>
            &copy; <span id="displayYear"></span> Все Права Защищены со
            <a href="https://html.design/">"Free Html Templates"</a><br><br>
            &copy; <span id="displayYear"></span>Распространяется По
            <a href="https://themewagon.com/" target="_blank">"ThemeWagon"</a>
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- added by backend-dev -->
  <script src="{% static 'js/carts.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>
</html>

templates/addPro.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Fast_food_website </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />



</head>

<div class="hero_area">
  <div class="bg-box">
    <img src="{% static 'images/hero-bg.jpg' %}" alt="">
  </div>
  <!-- header section strats -->
  <header class="header_section">
    <div class="container">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="{% url 'home' %}">
          <span>
            Feane
          </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>


        <div class="user_option">
          <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
            <g>
              <g>
                <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
              </g>
            </g>
            <g>
              <g>
                <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                C457.728,97.71,450.56,86.958,439.296,84.91z" />
              </g>
            </g>
            <g>
              <g>
                <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
              </g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
            <g>
            </g>
          </svg>
        </div>
      </nav>
    </div>
  </header>
<!-- end header section -->

<!-- book section -->
<section class="book_section layout_padding">
  <div class="container">
    <div class="heading_container">
      <h2 style="color: white">
        Product addition section
      </h2>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form_container">
          <form method="post" enctype="multipart/form-data"> {% csrf_token %}

            <p style="color: white">
              <label for="id_Name">Name:</label>
              <input class="form-control" placeholder="Product name"  type="text" name="Name" maxlength="100" required="" id="id_Name">
            </p>


            <p style="color: white">
              <label for="id_Description">Descreption:</label>
              <textarea class="form-control" placeholder="Product description" name="Descreption" cols="40" rows="10" required="" id="id_Descreption"></textarea>
            </p>


            <p style="color: white">
              <label for="id_Price">Price:</label>
              <input class="form-control" placeholder="Price" type="text" name="Price" maxlength="10" required="" id="id_Price">
            </p>

            <div style="color: white">
              <h2> Enter the image</h2>
              <br>
              <p>
                <input type="file" name='Image' accept="image/*" required="" id="id_Image">
              </p>
            </div>

            <p style="color: white">
              <button type="submit">Create</button>  
            </p>

          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end book section -->

<!-- footer section -->

<footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              Feane
            </a>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-pinterest" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            10.00 Am -10.00 Pm
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By
          <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
        </p>
      </div>
    </div>
  </footer>
</div>
</html>

    <!-- end footer section -->

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Fast_food_website </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- css files created by backend dev -->
  <link href="{% static 'css/style_2.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/view.css' %}" rel="stylesheet" type="text/css" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

 <script type="text/javascript"> 
  var user = '{{ request.user }}'

  function getToken(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}
var csrftoken = getToken('csrftoken');
  </script>
  
</head>

<div class="hero_area">
  <div class="bg-box-header" style="padding-top: 70px;">
    <img src="{% static 'images/fast-food.jpg' %}" alt="">
  </div>
  <!-- header section strats -->
  <header class="header_section">
    <div class="container">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="{% url 'home' %}">
          <span>
            MAX-BURGER
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav  mx-auto ">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'menu' %}">Меню</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">О нас</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'book' %}">Бук тэйбл</a>
            </li>
          </ul>
          <div class="user_option">
            {% if user.is_authenticated %}
            <div class="dropdown">
              <button class="dropbtn" id="add-to-cart1" style="margin-left: -100px"> {{ user.username|title }} </button>
              <style type="text/css">
                #add-to-cart1 {
                  border: 1px solid;
                  padding: 10px;
                  display: inline-block;
                  padding: 10px 45px;
                  background-color: #FF375B;
                  color: #ffffff;
                  border-radius: 45px;
                  -webkit-transition: all 0.3s;
                  transition: all 0.3s;
                  border: none;
                  margin-left: -30px;
                  margin-top: 10px;
                }

                #add-to-cart1:hover {
                  background-color: #fa2048;
                }
              </style>
              <div class="dropdown-content">
                <a href="#">Link 1</a>
                <a href='#'>Link 2</a>
                <a href="{% url 'logout' %}">Log out</a>
              </div>
              </style>
            </div>

            <div>
              <a href="{% url 'cart' %}">
                <img id="cart-icon" style="margin-left: 20px; width:90px;" src="{% static 'images/cartt.png' %}">
              </a>
              <p id="cart-total" style="margin-left: 54px; margin-top: -23px">{{ cartItems }}</p>
            </div>

            {% else %}
            <form class="form-inline ml-auto">

              <a href="{% url 'signup' %}" class="order_online" style="margin: 15px;">
              Зарегистрироваться</a>
              <a href="{% url 'login' %}" class="order_online">
              Войти</a>
            </form>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>
  </header>
  <!-- end header section -->

  {% block content %}

  {% endblock content %}
  <body>
    <footer class="footer_section">
      <div class="container">
        <div class="row">
          <div class="col-md-4 footer-col">
            <div class="footer_contact">
              <h4>
                Связаться с нами
              </h4>
              <div class="contact_link_box">
                <a href="">
                  <i class="fa fa-map-marker" aria-hidden="true"></i>
                  <span>
                    Местоположение
                  </span>
                </a>
                <a href="">
                  <i class="fa fa-phone" aria-hidden="true"></i>
                  <span>
                    Звоните (90) 722-95-29
                  </span>
                </a>
                <a href="">
                  <i class="fa fa-envelope" aria-hidden="true"></i>
                  <span>
                    mukhammadali222@gmail.com
                  </span>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-4 footer-col">
            <div class="footer_detail" >
              <a href="" class="footer-logo" style="border: solid 2px white; margin-bottom: 20px; padding: 5px 15px;
              ">
                MAX-BURGER 
              </a>
              <p style="color:white">
                Следует отметить, что синтетическое тестирование прекрасно подходит для реализации инновационных методов управления процессами
              </p>
            </div>
          </div>
          <div class="col-md-4 footer-col">
            <h4>
              Часы работы
            </h4>
            <p style="color:white">
              Ежедневный
            </p>
            <p style="color:white">
              10.00 - 22.00
            </p>
          </div>
        </div>
        <div class="footer-info">
          <p>
            &copy; <span id="displayYear"></span> Все Права Защищены со
            <a href="https://html.design/">"Free Html Templates"</a><br><br>
            &copy; <span id="displayYear"></span>Распространяется По
            <a href="https://themewagon.com/" target="_blank">"ThemeWagon"</a>
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- added by backend-dev -->
  <script src="{% static 'js/carts.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>
</html>